### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by luisdavim** [sensu-plugins/sensu-plugins-mesos#14]
Hi,

Is this still being maintained? There is is a fork that seems to be more up to date than this repo:
https://github.com/oskar-flores/sensu-plugins-mesos/tree/more-mesos-tasks

**Comment by luisdavim** [comment]
@oskar-flores are you still maintaining your fork? Are you planning on making a PR any time soon?

**Comment by majormoses** [comment]
Let me put it this way, I still plan on maintaining this. PRs are welcome.

**Comment by majormoses** [comment]
closing as we are actively maintaining it though rely heavily on community contributions. closed per #15
