### ISSUE TITLE
Package sensu-plugins-mesos for Bonsai

### ISSUE THREAD

**Issue by mgibson323** [sensu-plugins/sensu-plugins-mesos#43]
We'd like to get this plugin packaged and built for [Bonsai](https://bonsai.sensu.io/). 

Sensu internal ref: https://secure.helpscout.net/conversation/1626326345/27006/

**Comment by lrosenman** [comment]
This is my next-to-last thing needed to complete a migration to Sensu Go.  Can we get this sooner rather than later?  I'm willing to test.

**Comment by jspaleta** [comment]
I'll work on spinning up a test asset of this now and prepping the pr with the asset build automation for merge.

The entire sensu-plugins release automation needs to be overhauled and converted to github actions due to the problems at travisCI, just gonna take some time to get it sorted out.  In the meantime asset builds are gonna be a bit of a manual process.

**Comment by asachs01** [comment]
Circling back here. @lrosenman you should be able to deploy the asset using the definition here: https://cre-testing.s3.us-west-2.amazonaws.com/sensu-plugins-mesos/sensu-plugins-mesos.yaml. Can you validate that this indeed working for you? In order for the team to upload the asset to Bonsai, we need some sort of validation that you're able to actually deploy the asset using this definition and that it works as expected.

**Comment by lrosenman** [comment]
it's been deployed for MONTHS.

It's working great!

On 06/14/2022 2:54 pm, Aaron Sachs wrote:

> Circling back here. @lrosenman [1] you should be able to deploy the 
> asset using the definition here: 
> https://cre-testing.s3.us-west-2.amazonaws.com/sensu-plugins-mesos/sensu-plugins-mesos.yaml. 
> Can you validate that this indeed working for you? In order for the 
> team to upload the asset to Bonsai, we need some sort of validation 
> that you're able to actually deploy the asset using this definition and 
> that it works as expected.
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>

-- 
Larry Rosenman                     http://www.lerctr.org/~ler
Phone: +1 214-642-9640                 E-Mail: ***@***.***
US Mail: 5708 Sabbia Dr, Round Rock, TX 78665-2106


Links:
------
[1] https://github.com/lrosenman
[2] 
https://github.com/sensu-plugins/sensu-plugins-mesos/issues/43#issuecomment-1155650811
[3]

**Comment by jspaleta** [comment]
3.0.0-pre1 release built and available in bonsai now
